### PR TITLE
Add support for `EDGE_ALL` of margin / padding / borderWidth

### PR DESCRIPTION
**Pull request by jhen0409**
See the SVG file changes between the two commits. ([here](https://github.com/orta/jest-snapshots-svg/pull/37/commits/bc3e4db4f2cb693b35fe96126255fea06fd30518?short_path=dda0364#diff-dda0364ffa6c894447128d9cc3b3fcd3))

### CODE REVIEW

**Comment by jacobp100** [comment]
Good catch! I think we're also completely missing `borderWidth`. Should we do that here?

**Comment by jhen0409** [comment]
@jacobp100 Yeah it is also `EDGE_ALL` for `node.setBorder`, so I think it can be in this PR.

**Comment by orta** [comment]
👍

**Comment by jacobp100** [comment]
Thanks!

**Comment by orta** [comment]
Shipped as 0.0.24

**Pull request merged**
