### PR TITLE
Fix style property number `0` not set

### PR DESCRIPTION
**Pull request by jhen0409**
This is fix for #32.

### CODE REVIEW

**Comment by jacobp100** [comment]
I was just looking at a similar PR in `react-sketchapp` ([PR](https://github.com/airbnb/react-sketchapp/pull/188)). Should we try and support percentages too?

**Comment by jhen0409** [comment]
I think percentages should supported in yoga-layout, maybe we can change (or add) some tests for that.

**Comment by orta** [comment]
Shouldn't percentages just pass through?

**Comment by jacobp100** [comment]
Apparently not. There's `setMinWidthPercent` etc.

**Comment by jhen0409** [comment]
@jacobp100 I just saw [the handler](https://github.com/facebook/yoga/blob/master/javascript/sources/entry-common.js#L154-L155), so it should work by default.

**Comment by jacobp100** [comment]
Good catch!

**Comment by orta** [comment]
Published as `0.0.22`

**Comment by jhen0409** [comment]
@orta the changes looks not included in `0.0.22`.

**Comment by orta** [comment]
Interesting, tried another shot with `0.0.23`

**Pull request merged**
