### PR TITLE
Add support position style (absolute)

### PR DESCRIPTION
**Pull request by jhen0409**
https://facebook.github.io/yoga/docs/absolute-position

Added two tests in `example_layouts`.

### CODE REVIEW

**Comment by jhen0409** [comment]
Not sure why CI broken, it seems be problem in `yoga-layout` for Linux. (It works fine for me on macOS)

**Comment by orta** [comment]
Perfect, looks fine to me - thanks @jhen0409

**Comment by orta** [comment]
I'll get a release out

**Comment by orta** [comment]
Shipped as jest-snapshots-svg@0.0.15

**Pull request merged**
